' It retrieves information about patients in a hospital database on a specific day, including the hospital ID, department ID, 
department name, ward ID, ward name, bed ID, bed name, bed movement ID, bed movement date, bed release date, bed movement type,
 attendance ID, patient ID, and patient name. The results are filtered by hospital ID, whether the bed is extra, 
 bed activation date, bed deactivation date, and bed movement date, joined with the attendance and patient tables to retrieve 
 additional information, and ordered by hospital ID, department name, ward name, and bed name.'
SELECT
    BED_INFO.HOSPITAL_ID,
    BED_INFO.DEPARTMENT_ID,
    BED_INFO.DEPARTMENT_NAME,
    BED_INFO.WARD_ID,
    BED_INFO.WARD_NAME,
    BED_INFO.BED_ID,
    BED_INFO.BED_NAME,
    BED_MOVEMENT.ID AS BED_MOVEMENT_ID,
    BED_MOVEMENT.MOVEMENT_DATE,
    BED_MOVEMENT.RELEASE_DATE,
    BED_MOVEMENT.MOVEMENT_TYPE,
    BED_MOVEMENT.ATTENDANCE_ID,
    PATIENT.ID AS PATIENT_ID,
    PATIENT.NAME AS PATIENT_NAME
FROM (
    SELECT
        DEPARTMENT.HOSPITAL_ID,
        DEPARTMENT.ID AS DEPARTMENT_ID,
        DEPARTMENT.NAME AS DEPARTMENT_NAME,
        WARD.ID AS WARD_ID,
        WARD.NAME AS WARD_NAME,
        BED.ID AS BED_ID,
        BED.NAME AS BED_NAME
    FROM BED
    INNER JOIN WARD ON BED.WARD_ID = WARD.ID
    INNER JOIN DEPARTMENT ON WARD.DEPARTMENT_ID = DEPARTMENT.ID
    WHERE DEPARTMENT.HOSPITAL_ID IN (16,21,26)
    AND BED.IS_EXTRA = 'N'
    AND TRUNC(BED.ACTIVATION_DATE) < TRUNC(TO_DATE('2023-01-05 23:59:00','YYYY-MM-DD HH24:MI:SS'))
    AND TRUNC(NVL(BED.DEACTIVATION_DATE,SYSDATE)) >= TRUNC(TO_DATE('2023-01-05 23:59:00','YYYY-MM-DD HH24:MI:SS'))
) BED_INFO
LEFT JOIN (
    SELECT
        BED_MOVEMENT.ID,
        TO_CHAR(TRUNC(BED_MOVEMENT.MOVEMENT_DATE)+(BED_MOVEMENT.MOVEMENT_TIME-TRUNC(BED_MOVEMENT.MOVEMENT_TIME)),'YYYY-MM-DD HH24:MI:SS') AS MOVEMENT_DATE,
        TO_CHAR(TRUNC(BED_MOVEMENT.RELEASE_DATE)+(BED_MOVEMENT.RELEASE_TIME-TRUNC(BED_MOVEMENT.RELEASE_TIME)),'YYYY-MM-DD HH24:MI:SS') AS RELEASE_DATE,
        BED_MOVEMENT.MOVEMENT_TYPE,
        BED_MOVEMENT.BED_ID,
        BED_MOVEMENT.ATTENDANCE_ID
    FROM BED_MOVEMENT
    WHERE TRUNC(BED_MOVEMENT.MOVEMENT_DATE)+(BED_MOVEMENT.MOVEMENT_TIME-TRUNC(BED_MOVEMENT.MOVEMENT_TIME)) < TO_DATE('2023-01-05 23:59:00','YYYY-MM-DD HH24:MI:SS')
    AND (
        BED_MOVEMENT.RELEASE_DATE IS NULL
        OR
        TRUNC(BED_MOVEMENT.RELEASE_DATE)+(BED_MOVEMENT.RELEASE_TIME-TRUNC(BED_MOVEMENT.RELEASE_TIME)) >= TO_DATE('2023-01-05 23:59:00','YYYY-MM-DD HH24:MI:SS')
    )
    AND BED_MOVEMENT.BED_ID IN (
        SELECT
            BED.ID
        FROM BED
        INNER JOIN WARD ON BED.WARD_ID = WARD.ID
        INNER JOIN DEPARTMENT ON WARD.DEPARTMENT_ID = DEPARTMENT.ID
        WHERE DEPARTMENT.HOSPITAL_ID IN (16,21,26)
        AND BED.IS_EXTRA = 'N'
    )
) BED_MOVEMENT
ON BED_INFO.BED_ID = BED_MOVEMENT.BED_ID
LEFT JOIN ATTENDANCE ON BED_MOVEMENT.ATTENDANCE_ID = ATTENDANCE.ID
LEFT JOIN PATIENT ON ATTENDANCE.PATIENT_ID = PATIENT.ID