'It retrieves information about SIASUS events from a hospital database, including the hospital ID, attendance type,
 attendance ID, patient ID, patient name, SIASUS event date, SIASUS event ID, procedure organization group ID, 
 procedure group ID, procedure subgroup ID, procedure ID, and procedure description. The results are filtered by SIASUS 
 event date, hospital ID, procedure group ID, and procedure subgroup ID, and are ordered by hospital ID, procedure group ID,
  and procedure subgroup ID.'
SELECT
    HOSPITAL.ID AS HOSPITAL_ID,
    ATTENDANCE.TYPE AS ATTENDANCE_TYPE,
    ATTENDANCE.ID AS ATTENDANCE_ID,
    PATIENT.ID AS PATIENT_ID,
    PATIENT.NAME AS PATIENT_NAME,
    TO_CHAR(SIASUS_EVENT.DATE,'YYYY-MM-DD') AS SIASUS_EVENT_DATE,
    SIASUS_EVENT.ID AS SIASUS_EVENT_ID,
    PROCEDURE_ORGANIZATION_GROUP.ID AS PROCEDURE_ORGANIZATION_GROUP_ID,
    PROCEDURE_GROUP.ID AS PROCEDURE_GROUP_ID,
    PROCEDURE_SUBGROUP.ID AS PROCEDURE_SUBGROUP_ID,
    PROCEDURE.ID AS PROCEDURE_ID,
    PROCEDURE.DESCRIPTION AS PROCEDURE_DESCRIPTION
FROM SIASUS_EVENT
    LEFT JOIN PROCEDURE ON PROCEDURE.ID = SIASUS_EVENT.PROCEDURE_ID
    LEFT JOIN HOSPITAL ON HOSPITAL.ID = SIASUS_EVENT.HOSPITAL_ID
    LEFT JOIN ATTENDANCE ON ATTENDANCE.ID = SIASUS_EVENT.ATTENDANCE_ID
    LEFT JOIN PATIENT ON PATIENT.ID = ATTENDANCE.PATIENT_ID
WHERE TRUNC(SIASUS_EVENT.DATE) = TO_DATE($IAString01$,'YYYY-MM-DD') 
    AND HOSPITAL.ID IN (16,21,26)
    AND PROCEDURE_GROUP.ID IN ('04')
    AND PROCEDURE_SUBGROUP.ID IN ('01')
ORDER BY
    HOSPITAL.ID,
    PROCEDURE_GROUP.ID,
    PROCEDURE_SUBGROUP.ID