'It retrieves information about lab exams from a hospital database, including the hospital ID, attendance type, 
attendance ID, attendance date, patient ID, patient name, requesting department ID, requesting department name, 
executing department ID, executing department name, lab exam set ID, lab exam set name, lab request date, lab request ID, 
lab item date delivered, lab item ID, lab exam ID, and lab exam name. The results are filtered by lab item date delivered, 
hospital ID, and attendance type, and are ordered by hospital ID, attendance type, and attendance ID.'
SELECT
    HOSPITAL.ID AS HOSPITAL_ID,
    ATTENDANCE.TYPE AS ATTENDANCE_TYPE,
    ATTENDANCE.ID AS ATTENDANCE_ID,
    TO_CHAR(ATTENDANCE.DATE,'YYYY-MM-DD') AS ATTENDANCE_DATE,
    PATIENT.ID AS PATIENT_ID,
    PATIENT.NAME AS PATIENT_NAME,
    REQUESTING_DEPARTMENT.ID AS REQUESTING_DEPARTMENT_ID,
    REQUESTING_DEPARTMENT.NAME AS REQUESTING_DEPARTMENT_NAME,
    EXECUTING_DEPARTMENT.ID AS EXECUTING_DEPARTMENT_ID,
    EXECUTING_DEPARTMENT.NAME AS EXECUTING_DEPARTMENT_NAME,
    LAB_EXAM_SET.ID AS LAB_EXAM_SET_ID,
    LAB_EXAM_SET.NAME AS LAB_EXAM_SET_NAME,
    TO_CHAR(LAB_REQUEST.DATE,'YYYY-MM-DD') AS LAB_REQUEST_DATE,
    LAB_REQUEST.ID AS LAB_REQUEST_ID,
    TO_CHAR(LAB_ITEM.DATE_DELIVERED,'YYYY-MM-DD') AS LAB_ITEM_DATE_DELIVERED,
    LAB_ITEM.ID AS LAB_ITEM_ID,
    LAB_EXAM.ID AS LAB_EXAM_ID,
    LAB_EXAM.NAME AS LAB_EXAM_NAME
FROM ATTENDANCE
    LEFT JOIN PATIENT ON ATTENDANCE.PATIENT_ID = PATIENT.ID
    LEFT JOIN LAB_REQUEST ON ATTENDANCE.ID = LAB_REQUEST.ATTENDANCE_ID
    LEFT JOIN DEPARTMENT AS REQUESTING_DEPARTMENT ON REQUESTING_DEPARTMENT.ID = LAB_REQUEST.DEPARTMENT_ID
    LEFT JOIN LAB_EXAM_SET ON LAB_EXAM_SET.ID = LAB_REQUEST.LAB_EXAM_SET_ID
    LEFT JOIN DEPARTMENT AS EXECUTING_DEPARTMENT ON EXECUTING_DEPARTMENT.ID = LAB_EXAM_SET.DEPARTMENT_ID
    LEFT JOIN LAB_ITEM ON LAB_ITEM.LAB_REQUEST_ID = LAB_REQUEST.ID
    LEFT JOIN LAB_EXAM ON LAB_ITEM.LAB_EXAM_ID = LAB_EXAM.ID
WHERE TRUNC(LAB_ITEM.DATE_DELIVERED) = TO_DATE('2023-01-05','YYYY-MM-DD')
    AND HOSPITAL.ID IN (16,21,26)
    AND ATTENDANCE.TYPE IN ('A','E')
ORDER BY
    HOSPITAL.ID,
    ATTENDANCE.TYPE,
    ATTENDANCE.ID