'It retrieves information about surgery cancellations from a hospital database, including the hospital ID, surgery notice ID,
 notice date, cancel date, attendance ID, patient ID, patient name, surgery ID, surgery description, cancel reason ID, 
 cancel reason description, cancel reason type, and the origin of the cancellation (patient or hospital). 
 The results are filtered by hospital ID and cancel date, and are ordered by hospital ID and surgery notice ID.'
SELECT
    HOSPITAL.ID AS HOSPITAL_ID,
    SURGERY_NOTICE.ID AS SURGERY_NOTICE_ID,
    TO_CHAR(SURGERY_NOTICE.NOTICE_DATE,'YYYY-MM-DD HH24:MI:SS') AS NOTICE_DATE,
    TO_CHAR(SURGERY_NOTICE.CANCEL_DATE,'YYYY-MM-DD HH24:MI:SS') AS CANCEL_DATE,
    ATTENDANCE.ID AS ATTENDANCE_ID,
    PATIENT.ID AS PATIENT_ID,
    PATIENT.NAME AS PATIENT_NAME,
    SURGERY.ID AS SURGERY_ID,
    SURGERY.DESCRIPTION AS SURGERY_DESCRIPTION,
    CANCEL_REASON.ID AS CANCEL_REASON_ID,
    CANCEL_REASON.DESCRIPTION AS CANCEL_REASON_DESCRIPTION,
    CANCEL_REASON.TYPE AS CANCEL_REASON_TYPE,
    CASE WHEN CANCEL_REASON.TYPE IN ('P') THEN 'PATIENT' ELSE 'HOSPITAL' END AS CANCEL_ORIGIN
FROM HOSPITAL
LEFT JOIN SURGERY_NOTICE ON HOSPITAL.ID = SURGERY_NOTICE.HOSPITAL_ID
LEFT JOIN SURGERY ON SURGERY_NOTICE.SURGERY_ID = SURGERY.ID
LEFT JOIN CANCEL_REASON ON SURGERY_NOTICE.CANCEL_REASON_ID = CANCEL_REASON.ID
WHERE HOSPITAL.ID IN (16,21,26)
AND TRUNC(SURGERY_NOTICE.CANCEL_DATE) = TO_DATE($IAString01$,'YYYY-MM-DD')
ORDER BY
    HOSPITAL.ID,
    SURGERY_NOTICE.ID